source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'DZLayoutTable', :exclusive => true do
  pod "DZLayoutTable", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DZLayoutTable", :path => "../"

  pod 'FBSnapshotTestCase'
end
